using ReScene.NET.Helpers;

namespace ReScene.NET.Tests;

public class FormatUtilitiesTests
{
    [Fact]
    public void NormalizeAppName_AutoGeneratedValue_RefreshesToLiveDefault()
    {
        string stale = "ReScene.NET v1.5.0 (92f6e9f)";
        string result = FormatUtilities.NormalizeAppName(stale);
        Assert.Equal(FormatUtilities.GetDefaultAppName(), result);
        Assert.NotEqual(stale, result);
    }

    [Fact]
    public void NormalizeAppName_Blank_ReturnsLiveDefault()
    {
        Assert.Equal(FormatUtilities.GetDefaultAppName(), FormatUtilities.NormalizeAppName(""));
        Assert.Equal(FormatUtilities.GetDefaultAppName(), FormatUtilities.NormalizeAppName(null));
        Assert.Equal(FormatUtilities.GetDefaultAppName(), FormatUtilities.NormalizeAppName("   "));
    }

    [Fact]
    public void NormalizeAppName_CustomValue_IsUnchanged()
    {
        Assert.Equal("MyGroup", FormatUtilities.NormalizeAppName("MyGroup"));
    }
}
